mdAPIZip/zipfile/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Additional_Room__c</fullName>
        <label>Additional Room</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1Bedroom</fullName>
                </value>
                <value>
                    <fullName>2Bedroom</fullName>
                </value>
                <value>
                    <fullName>3Bedroom</fullName>
                </value>
                <value>
                    <fullName>1Bedroom +1Kitchen</fullName>
                </value>
                <value>
                    <fullName>2Bedroom +1Kitchen</fullName>
                </value>
                <value>
                    <fullName>3Bedroom+1Kitchen</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Available_From__c</fullName>
        <label>Available From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Electricity_Status__c</fullName>
        <label>Electricity Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Facing__c</fullName>
        <label>Facing</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Floor__c</fullName>
        <label>Floor</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>For_Bachellor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>For Bachellor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>For_Family__c</fullName>
        <label>For Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Main_Image__c</fullName>
        <label>Property Main Image</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

mdAPIZip/zipfile/classes/Property.cls
public with sharing class Property {
    @AuraEnabled(cacheable=true)
    public static List<Property__c> getLatestProperty()
    {
        System.debug('******GetLatestPropety*****');
        List<Property__c> latestProperty = [Select Id,Additional_Room__c,Property_Main_Image__c,Available_From__c,Electricity_Status__c,Facing__c,Floor__c,For_Bachellor__c,For_Family__c FROM Property__c LIMIT50];
        System.debug('List Found '+latestProperty);
        return latestProperty;
      
        //return [Select Name, Phone, Email From Contact limit 20]; 
    }
}